pipeline {
    agent any
    stages {
        stage('Clone github repository') {
            steps {
                git branch: 'main', url: 'https://github.com/max360britain/Jenkins.git'
            }
        }
        stage('Create s3 bucket') {
            steps {
                withCredentials([aws(accessKeyVariable: 'AWS_ACCESS_KEY_ID', credentialsId: 'Jenkins-aws-cred', secretKeyVariable: 'AWS_SECRET_ACCESS_KEY')]) {
                aws s3 mb s3://Cloud-House-bucket-1
                sleep 60
}

            }
        }
        stage('List s3 bucket for confirmation') {
            steps {
                withCredentials([aws(accessKeyVariable: 'AWS_ACCESS_KEY_ID', credentialsId: 'Jenkins-aws-cred', secretKeyVariable: 'AWS_SECRET_ACCESS_KEY')]) {
                aws s3 ls
                sleep 60
}

            }
        }

        stage('Delete s3 bucket') {
            steps {
                withCredentials([aws(accessKeyVariable: 'AWS_ACCESS_KEY_ID', credentialsId: 'Jenkins-aws-cred', secretKeyVariable: 'AWS_SECRET_ACCESS_KEY')]) {
                aws s3 rb s3://Cloud-House-bucket-1
                sleep 60
}
            }
        }
    }
}